# Generated by Django 4.2.6 on 2023-10-11 05:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.IntegerField()),
                ('question', models.CharField(max_length=256, unique=True)),
                ('answer', models.CharField(max_length=256, unique=True)),
                ('created_at', models.DateTimeField()),
                ('inserted_at', models.DateTimeField(default=datetime.date(2023, 10, 11))),
            ],
        ),
    ]
